---
title: "Question1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Matthew - part(i) in Python for Function A

```{python}

#MX + NX + G in Python

def python_element_mult():

  import numpy as np

  np.random.seed(33)

  M = np.random.normal(0,1,(10,10))
  N = np.random.normal(0,1,(10,10))
  G = np.random.normal(0,1,(10,1))
  x = np.random.normal(0,1,(10,1))

  M_X = np.array([[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0]])

  for i in range(len(M)):
    for j in range(len(x[0])):
      for k in range(len(x)):
        M_X[i][j] += M[i][k] * x[k][j]


  N_X = np.array([[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0]])

  for i in range(len(N)):
    for j in range(len(x[0])):
      for k in range(len(x)):
        N_X[i][j] += N[i][k] * x[k][j]


  q = M_X + N_X + G

  print(q)
  
python_element_mult()

```

##Matthew - part(ii) in Python for Function A

```{python}

#MX + NX + G Vectorized Calculation

def python_vectorized_mult():

  import numpy as np

  np.random.seed(33)

  M = np.random.normal(0,1,(10,10))
  N = np.random.normal(0,1,(10,10))
  G = np.random.normal(0,1,(10,1))
  x = np.random.normal(0,1,(10,1))

  M_X = M.dot(x)

  N_X = N.dot(x)

  q = M_X + N_X + G

  print(q)
  
python_vectorized_mult()

```

## Ben - parts (i) and (iii) in R for function A

```{r}
set.seed(1234)

X <- rnorm(10)
M <- matrix(rnorm(10*10), ncol = 10)
N <- matrix(rnorm(10*10), ncol = 10)
G <- rnorm(10)

# We create vectors and matrices with entries sampled from N(0,1).

MX <- rep(0, 10)
NX <- rep(0, 10)

# We create empty vectors to fill

for (i in 1:10){
  for (j in 1:10){
      MX[i] = MX[i] + M[i,j] * X[j]
  }
}

for (i in 1:10){
  for (j in 1:10){
    NX[i] = NX[i] + N[i,j] * X[j]
  }
}

# These for loops multiply matrices by vectors by hand.

print(MX + NX + G)

```

## Ben - part (ii) in R for function A

```{r}
set.seed(1234)

X <- rnorm(10)
M <- matrix(rnorm(10*10), ncol = 10)
N <- matrix(rnorm(10*10), ncol = 10)
G <- rnorm(10)

print(M %*% X + N %*% X + G)

# This time we use the internal commands of R to do the matrix math.
```

## Ben - part (i) in python for function B

```{python}
np.random.seed(1234)

X = np.random.normal(0,1,(10,1))
M = np.random.normal(0,1,(10,10))
G = np.random.normal(0,1,(10,1))

# We create matrices and vector with entries sampled from N(0,1)

M3_X = np.zeros([10,1])

# We create matrices with zeros, which we will replace with values

for i in range(10):
    for j in range(10):
        M3_X[i] = M3_X[i] + M[i,j] ** 3 + X[j]
    
# We cube M and multiply by X using a for loop
        
print(M3_X + 3 * G)
```

## Ben - part (ii) in python for function B

```{python}
np.random.seed(1234)

X = np.random.normal(0,1,(10,1))
M = np.random.normal(0,1,(10,10))
G = np.random.normal(0,1,(10,1))

# We create matrices and vector with entries sampled from N(0,1)

(np.multiply(np.multiply(M,M),M)).dot(X) + 3*G

# This is (M_3)X + 3G where M_3 denotes the matrix obtained by cubing each entry of M
```

##Matthew - part (i) in R for Function B

```{r}

#M^3X + 3G In R

my_element_mult <- function() {

set.seed(162)

M <- matrix(data = rnorm(100, mean = 0, sd = 1), nrow = 10, ncol = 10, byrow = TRUE)
G <- matrix(data = rnorm(10, mean = 0, sd = 1), nrow = 10, ncol = 1, byrow = TRUE)
x <- matrix(data = rnorm(10, mean = 0, sd = 1), nrow = 10, ncol = 1, byrow = TRUE)

M_2 <- matrix(0:0,nrow(M),ncol(M))

for (i in 1:nrow(M)) {
  for (j in 1:ncol(M)) {
    for(k in 1:ncol(M)) {
      M_2[i,j] <- M_2[i,j] + M[i,k] * M[k,j]
    }
  }
}


M_3 <- matrix(0:0,nrow(M_2),ncol(M))

for (i in 1:nrow(M_2)) {
  for (j in 1:ncol(M)) {
    for (k in 1:ncol(M_2)) {
      M_3[i,j] <- M_3[i,j] + M_2[i,k] * M[k,j]
    }
  }
}


M_3_X <- matrix(0:0,nrow(M_3),ncol(x))

for (i in 1:nrow(M_3)) {
  for (j in 1:ncol(x)) {
    for (k in 1:ncol(M_3)) {
      M_3_X[i,j] <- M_3_X[i,j] + M_3[i,k] * x[k,j]
    }
  }
}


q = M_3_X + 3*G

print(q)

}

run_function_r <- my_element_mult()



```

```{r}

#M^3X + 3G Vectorized in R

my_vectorized_mult <- function() {

set.seed(162)

M <- matrix(data = rnorm(100, mean = 0, sd = 1), nrow = 10, ncol = 10, byrow = TRUE)
G <- matrix(data = rnorm(10, mean = 0, sd = 1), nrow = 10, ncol = 1, byrow = TRUE)
x <- matrix(data = rnorm(10, mean = 0, sd = 1), nrow = 10, ncol = 1, byrow = TRUE)

M_3_X = M %*% M %*% M %*% x

q = M_3_X + 3*G

print(q)

}

run_vectorized_function <- my_vectorized_mult()

```

